version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "17:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: all
    commit-message:
      prefix: "chore"
      include: "scope"
